#Workflow configuration for Playwright tests
# This workflow runs Playwright tests on push and pull request events to the main branch.
name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --reporter=json
    - uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: results.json
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
